/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{html,js,ts}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#7d2d00",
        "surface-dim": "#0b1326",
        "inverse-surface": "#dae2fd",
        "on-background": "#dae2fd",
        "surface-container-low": "#131b2e",
        "secondary-fixed": "#c4e7ff",
        "on-primary-container": "#eeefff",
        "surface-bright": "#31394d",
        "primary": "#b4c5ff",
        "surface-container-high": "#222a3d",
        "secondary-container": "#00a6e0",
        "surface": "#0b1326",
        "outline-variant": "#434655",
        "secondary-fixed-dim": "#7bd0ff",
        "on-secondary": "#00354a",
        "on-secondary-fixed-variant": "#004c69",
        "on-secondary-fixed": "#001e2c",
        "surface-container": "#171f33",
        "on-error": "#690005",
        "on-surface": "#dae2fd",
        "surface-variant": "#2d3449",
        "on-tertiary-container": "#ffede6",
        "primary-container": "#2563eb",
        "tertiary": "#ffb596",
        "error": "#ffb4ab",
        "surface-container-highest": "#2d3449",
        "tertiary-fixed-dim": "#ffb596",
        "on-secondary-container": "#00374d",
        "on-surface-variant": "#c3c6d7",
        "tertiary-fixed": "#ffdbcd",
        "on-error-container": "#ffdad6",
        "inverse-primary": "#0053db",
        "surface-container-lowest": "#060e20",
        "inverse-on-surface": "#283044",
        "on-primary-fixed": "#00174b",
        "outline": "#8d90a0",
        "on-tertiary-fixed": "#360f00",
        "primary-fixed-dim": "#b4c5ff",
        "on-primary-fixed-variant": "#003ea8",
        "surface-tint": "#b4c5ff",
        "error-container": "#93000a",
        "primary-fixed": "#dbe1ff",
        "background": "#0b1326",
        "on-primary": "#002a78",
        "on-tertiary": "#581e00",
        "secondary": "#7bd0ff",
        "tertiary-container": "#bc4800",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-mobile": "20px",
        "margin-desktop": "40px",
        "section-gap": "120px",
        gutter: "24px",
        "container-max": "1200px",
        unit: "8px",
      },
      fontFamily: {
        "display-lg": ["Inter"],
        "label-mono": ["JetBrains Mono"],
        "headline-md": ["Inter"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "display-lg-mobile": ["Inter"],
      },
      fontSize: {
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        "label-mono": ["14px", { lineHeight: "1.4", letterSpacing: "0.02em", fontWeight: "500" }],
        "headline-md": ["32px", { lineHeight: "1.3", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "display-lg-mobile": ["40px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
