/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{html,js,ts}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#52525b",
        "surface-dim": "#050505",
        "inverse-surface": "#fafafa",
        "on-background": "#fafafa",
        "surface-container-low": "#0e0e10",
        "secondary-fixed": "#f4f4f5",
        "on-primary-container": "#fafafa",
        "surface-bright": "#18181b",
        "primary": "#ffffff",
        "surface-container-high": "#161619",
        "secondary-container": "#18181b",
        "surface": "#09090b",
        "outline-variant": "#18181b",
        "secondary-fixed-dim": "#e4e4e7",
        "on-secondary": "#09090b",
        "on-secondary-fixed-variant": "#3f3f46",
        "on-secondary-fixed": "#09090b",
        "surface-container": "#121214",
        "on-surface": "#fafafa",
        "surface-variant": "#18181b",
        "on-tertiary-container": "#fafafa",
        "primary-container": "#27272a",
        "tertiary": "#717172",
        "error": "#ffb4ab",
        "surface-container-highest": "#202024",
        "tertiary-fixed-dim": "#d4d4d8",
        "on-secondary-container": "#fafafa",
        "on-surface-variant": "#d4d4d8",
        "tertiary-fixed": "#f4f4f5",
        "on-error-container": "#ffdad6",
        "inverse-primary": "#e4e4e7",
        "surface-container-lowest": "#000000",
        "inverse-on-surface": "#18181b",
        "on-primary-fixed": "#09090b",
        "outline": "#27272a",
        "on-tertiary-fixed": "#ffffff",
        "primary-fixed-dim": "#c7d2fe",
        "on-primary-fixed-variant": "#52525b",
        "surface-tint": "#ffffff",
        "error-container": "#93000a",
        "primary-fixed": "#e0e7ff",
        "background": "#09090b",
        "on-primary": "#09090b",
        "on-tertiary": "#ffffff",
        "secondary": "#a1a1aa",
        "tertiary-container": "#27272a",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-mobile": "20px",
        "margin-desktop": "40px",
        "section-gap": "120px",
        gutter: "24px",
        "container-max": "1200px",
        unit: "8px",
      },
      fontFamily: {
        "display-lg": ["Inter"],
        "label-mono": ["JetBrains Mono"],
        "headline-md": ["Inter"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "display-lg-mobile": ["Inter"],
      },
      fontSize: {
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        "label-mono": ["14px", { lineHeight: "1.4", letterSpacing: "0.02em", fontWeight: "500" }],
        "headline-md": ["32px", { lineHeight: "1.3", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "display-lg-mobile": ["40px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
